version: '3.1'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo-db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    working_dir: /app-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/app-mongo
    
